name: Compile and Deploy Java API to Maven Central

on:
  push:
    branches:
      - keyple-less-client
  workflow_dispatch:

jobs:
  java-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_API_TOKEN }}
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.OSSRH_GPG_SECRET_PASSWORD }}

      - name: Install GPG secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --pinentry-mode loopback --passphrase "${{ secrets.OSSRH_GPG_SECRET_PASSWORD }}" --export-secret-key 568FD16F857171A0EC6D2C40742C84722FD2B235 > ~/.gradle/maven-central.gpg
          gpg --list-secret-keys --keyid-format LONG

      - name: Update permissions
        run: chmod +x ./gradlew ./.github/scripts/*.sh

      - name: Check version
        run: ./.github/scripts/check_version.sh

      - name: Build and Publish
        run: ./gradlew build test publish --info --stacktrace
